name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        name: Set cache files
        id: cache-source
        with:
          path: compiled
          key: ${{ runner.os }}-jfile-manager
      - name: Build Application
        if: steps.cache-source.outputs.cache-hit != 'true'
        run: |
          npm install
          npx qx compile
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: jorgejuareznet/jfile-manager:latest
